//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiaParser.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActiaParser.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and Get result.
        /// </summary>
        internal static string AndGetResult {
            get {
                return ResourceManager.GetString("AndGetResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and STOP capture.
        /// </summary>
        internal static string AndStopCapture {
            get {
                return ResourceManager.GetString("AndStopCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        internal static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at cell.
        /// </summary>
        internal static string AtCell {
            get {
                return ResourceManager.GetString("AtCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at line.
        /// </summary>
        internal static string AtLine {
            get {
                return ResourceManager.GetString("AtLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at row.
        /// </summary>
        internal static string AtRow {
            get {
                return ResourceManager.GetString("AtRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel action.
        /// </summary>
        internal static string ChannelAction {
            get {
                return ResourceManager.GetString("ChannelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action after capture.
        /// </summary>
        internal static string ChannelActionAfterCapture {
            get {
                return ResourceManager.GetString("ChannelActionAfterCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action Capture.
        /// </summary>
        internal static string ChannelActionCapture {
            get {
                return ResourceManager.GetString("ChannelActionCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action Capture HIGHLOW START.
        /// </summary>
        internal static string ChannelActionCaptureHighLowStart {
            get {
                return ResourceManager.GetString("ChannelActionCaptureHighLowStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action Capture HIGHLOW STOP.
        /// </summary>
        internal static string ChannelActionCaptureHighLowStop {
            get {
                return ResourceManager.GetString("ChannelActionCaptureHighLowStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action Capture MAX START.
        /// </summary>
        internal static string ChannelActionCaptureMaxStart {
            get {
                return ResourceManager.GetString("ChannelActionCaptureMaxStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action Capture MAX STOP.
        /// </summary>
        internal static string ChannelActionCaptureMaxStop {
            get {
                return ResourceManager.GetString("ChannelActionCaptureMaxStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action Overload delay.
        /// </summary>
        internal static string ChannelActionOverloadDelay {
            get {
                return ResourceManager.GetString("ChannelActionOverloadDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action Overload Max Test.
        /// </summary>
        internal static string ChannelActionOverloadMaxTest {
            get {
                return ResourceManager.GetString("ChannelActionOverloadMaxTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action Overload Max Test Reset.
        /// </summary>
        internal static string ChannelActionOverloadMaxTestReset {
            get {
                return ResourceManager.GetString("ChannelActionOverloadMaxTestReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action Overload Max Test Setup.
        /// </summary>
        internal static string ChannelActionOverloadMaxTestSetup {
            get {
                return ResourceManager.GetString("ChannelActionOverloadMaxTestSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action Overload Mode Start.
        /// </summary>
        internal static string ChannelActionOverloadModeStart {
            get {
                return ResourceManager.GetString("ChannelActionOverloadModeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action Overload Mode Stop.
        /// </summary>
        internal static string ChannelActionOverloadModeStop {
            get {
                return ResourceManager.GetString("ChannelActionOverloadModeStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action Overload Rating Test.
        /// </summary>
        internal static string ChannelActionOverloadRatingTest {
            get {
                return ResourceManager.GetString("ChannelActionOverloadRatingTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action Overload Rating Test Reset.
        /// </summary>
        internal static string ChannelActionOverloadRatingTestReset {
            get {
                return ResourceManager.GetString("ChannelActionOverloadRatingTestReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action Overload Rating Test Setup.
        /// </summary>
        internal static string ChannelActionOverloadRatingTestSetup {
            get {
                return ResourceManager.GetString("ChannelActionOverloadRatingTestSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action reset.
        /// </summary>
        internal static string ChannelActionReset {
            get {
                return ResourceManager.GetString("ChannelActionReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action reset prerequire.
        /// </summary>
        internal static string ChannelActionResetPrerequire {
            get {
                return ResourceManager.GetString("ChannelActionResetPrerequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action Result.
        /// </summary>
        internal static string ChannelActionResult {
            get {
                return ResourceManager.GetString("ChannelActionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action Set prerequire.
        /// </summary>
        internal static string ChannelActionSetPrerequire {
            get {
                return ResourceManager.GetString("ChannelActionSetPrerequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action Setter.
        /// </summary>
        internal static string ChannelActionSetter {
            get {
                return ResourceManager.GetString("ChannelActionSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action start.
        /// </summary>
        internal static string ChannelActionStart {
            get {
                return ResourceManager.GetString("ChannelActionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Action stop.
        /// </summary>
        internal static string ChannelActionStop {
            get {
                return ResourceManager.GetString("ChannelActionStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This condition cannot be tested because of high resitive range of.
        /// </summary>
        internal static string ConditionCannotBeTestedManually {
            get {
                return ResourceManager.GetString("ConditionCannotBeTestedManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to counter it should have increase by 1Km.
        /// </summary>
        internal static string CounterItShouldHaveIncreaseBy1Km {
            get {
                return ResourceManager.GetString("CounterItShouldHaveIncreaseBy1Km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay after.
        /// </summary>
        internal static string DelayAfter {
            get {
                return ResourceManager.GetString("DelayAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay after set prerequire.
        /// </summary>
        internal static string DelayAfterPrerequire {
            get {
                return ResourceManager.GetString("DelayAfterPrerequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay after set prerequire to NONE on test line.
        /// </summary>
        internal static string DelayAfterPrerquireNone {
            get {
                return ResourceManager.GetString("DelayAfterPrerquireNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay before checking CAN forward.
        /// </summary>
        internal static string DelayBeforeCheckingCanForward {
            get {
                return ResourceManager.GetString("DelayBeforeCheckingCanForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay before start capture.
        /// </summary>
        internal static string DelayBeforeStartCapture {
            get {
                return ResourceManager.GetString("DelayBeforeStartCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay before testing message.
        /// </summary>
        internal static string DelayBeforeTestingMessage {
            get {
                return ResourceManager.GetString("DelayBeforeTestingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay between Set and result of.
        /// </summary>
        internal static string DelayBetweenSetAndResultOf {
            get {
                return ResourceManager.GetString("DelayBetweenSetAndResultOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay between STOP Capture.
        /// </summary>
        internal static string DelayBetweenStopCapture {
            get {
                return ResourceManager.GetString("DelayBetweenStopCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay for capture MAX of.
        /// </summary>
        internal static string DelayForCaptureMaxOf {
            get {
                return ResourceManager.GetString("DelayForCaptureMaxOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay for odometer.
        /// </summary>
        internal static string DelayForOdometer {
            get {
                return ResourceManager.GetString("DelayForOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay for overload capture after.
        /// </summary>
        internal static string DelayForOverloadCaptureAfter {
            get {
                return ResourceManager.GetString("DelayForOverloadCaptureAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELAY of.
        /// </summary>
        internal static string DelayOf {
            get {
                return ResourceManager.GetString("DelayOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay after reset prerequire on test line.
        /// </summary>
        internal static string DelayResetPrerequire {
            get {
                return ResourceManager.GetString("DelayResetPrerequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay START Capture.
        /// </summary>
        internal static string DelaySartCapture {
            get {
                return ResourceManager.GetString("DelaySartCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay WIPER_INTERVAL.
        /// </summary>
        internal static string DelayWiperInterval {
            get {
                return ResourceManager.GetString("DelayWiperInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay WIPER_WASH.
        /// </summary>
        internal static string DelayWiperWash {
            get {
                return ResourceManager.GetString("DelayWiperWash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay WIPER_WASH before getting result.
        /// </summary>
        internal static string DelayWiperWashBeforeGettingResult {
            get {
                return ResourceManager.GetString("DelayWiperWashBeforeGettingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you.
        /// </summary>
        internal static string DoYou {
            get {
                return ResourceManager.GetString("DoYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in channel ID.
        /// </summary>
        internal static string ErrorInChannelID {
            get {
                return ResourceManager.GetString("ErrorInChannelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error the Voltage set is too high.
        /// </summary>
        internal static string ErrorTheVoltageSetIsTooHigh {
            get {
                return ResourceManager.GetString("ErrorTheVoltageSetIsTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with can sender.
        /// </summary>
        internal static string ErrorWithCanSender {
            get {
                return ResourceManager.GetString("ErrorWithCanSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forwared check error.
        /// </summary>
        internal static string ForwaredCheckError {
            get {
                return ResourceManager.GetString("ForwaredCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hear.
        /// </summary>
        internal static string Hear {
            get {
                return ResourceManager.GetString("Hear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No board found for this channel.
        /// </summary>
        internal static string NoBoardFoundForThisChannel {
            get {
                return ResourceManager.GetString("NoBoardFoundForThisChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open resistive channels.
        /// </summary>
        internal static string OpenResistiveChannels {
            get {
                return ResourceManager.GetString("OpenResistiveChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the cluster.
        /// </summary>
        internal static string PleaseCheckTheCluster {
            get {
                return ResourceManager.GetString("PleaseCheckTheCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the cluster time and compare it with.
        /// </summary>
        internal static string PleaseCheckTheClusterTimeAndCompareItWith {
            get {
                return ResourceManager.GetString("PleaseCheckTheClusterTimeAndCompareItWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the cluster time and compare it with your watch.
        /// </summary>
        internal static string PleaseCheckTheClusterTimeAndCompareItWithYourWatch {
            get {
                return ResourceManager.GetString("PleaseCheckTheClusterTimeAndCompareItWithYourWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , please test it manually.
        /// </summary>
        internal static string PleaseTestItManually {
            get {
                return ResourceManager.GetString("PleaseTestItManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psu Action.
        /// </summary>
        internal static string PsuAction {
            get {
                return ResourceManager.GetString("PsuAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive CAN forward.
        /// </summary>
        internal static string ReceiveCanForward {
            get {
                return ResourceManager.GetString("ReceiveCanForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset DM1 Data1 Frame for test.
        /// </summary>
        internal static string ResetDM1Data1FrameForTest {
            get {
                return ResourceManager.GetString("ResetDM1Data1FrameForTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset DM1 Data2 Frame for test.
        /// </summary>
        internal static string ResetDM1Data2FrameForTest {
            get {
                return ResourceManager.GetString("ResetDM1Data2FrameForTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset DM1 Frame for test.
        /// </summary>
        internal static string ResetDM1FrameForTest {
            get {
                return ResourceManager.GetString("ResetDM1FrameForTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset DM1 Header Frame for test.
        /// </summary>
        internal static string ResetDM1HeaderFrameForTest {
            get {
                return ResourceManager.GetString("ResetDM1HeaderFrameForTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of.
        /// </summary>
        internal static string ResultOf {
            get {
                return ResourceManager.GetString("ResultOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see.
        /// </summary>
        internal static string See {
            get {
                return ResourceManager.GetString("See", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Default CanLoop.
        /// </summary>
        internal static string SendDefaultCanLoop {
            get {
                return ResourceManager.GetString("SendDefaultCanLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send DM1 Data1 Frame for test.
        /// </summary>
        internal static string SendDM1Data1FrameForTest {
            get {
                return ResourceManager.GetString("SendDM1Data1FrameForTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send DM1 Data2 Frame for test.
        /// </summary>
        internal static string SendDM1Data2FrameForTest {
            get {
                return ResourceManager.GetString("SendDM1Data2FrameForTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send DM1 Frame for test.
        /// </summary>
        internal static string SendDM1FrameForTest {
            get {
                return ResourceManager.GetString("SendDM1FrameForTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send DM1 Header Frame for test.
        /// </summary>
        internal static string SendDM1HeaderFrameForTest {
            get {
                return ResourceManager.GetString("SendDM1HeaderFrameForTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set channel.
        /// </summary>
        internal static string SetChannel {
            get {
                return ResourceManager.GetString("SetChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default value for.
        /// </summary>
        internal static string SetDefaultValueFor {
            get {
                return ResourceManager.GetString("SetDefaultValueFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET wiper.
        /// </summary>
        internal static string SetWiper {
            get {
                return ResourceManager.GetString("SetWiper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signal.
        /// </summary>
        internal static string Signal {
            get {
                return ResourceManager.GetString("Signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start CanLoop.
        /// </summary>
        internal static string StartCanLoop {
            get {
                return ResourceManager.GetString("StartCanLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Default CanLoop.
        /// </summary>
        internal static string StartDefaultCanLoop {
            get {
                return ResourceManager.GetString("StartDefaultCanLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        internal static string STOP {
            get {
                return ResourceManager.GetString("STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop CanLoop.
        /// </summary>
        internal static string StopCanLoop {
            get {
                return ResourceManager.GetString("StopCanLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Default CanLoop.
        /// </summary>
        internal static string StopDefaultCanLoop {
            get {
                return ResourceManager.GetString("StopDefaultCanLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test can sender signal.
        /// </summary>
        internal static string TestCanSenderSignal {
            get {
                return ResourceManager.GetString("TestCanSenderSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message has not been associated to one CAN channel.
        /// </summary>
        internal static string TheMessageHasNotBeenAssociatedToOneCanChannel {
            get {
                return ResourceManager.GetString("TheMessageHasNotBeenAssociatedToOneCanChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message has not been associated to one CAN channel in sheet.
        /// </summary>
        internal static string TheMessageHasNotBeenAssociatedToOneCanChannelInSheet {
            get {
                return ResourceManager.GetString("TheMessageHasNotBeenAssociatedToOneCanChannelInSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ressources is not available in your project.
        /// </summary>
        internal static string ThisRessourcesIsNotAvailableInYourProject {
            get {
                return ResourceManager.GetString("ThisRessourcesIsNotAvailableInYourProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With.
        /// </summary>
        internal static string With {
            get {
                return ResourceManager.GetString("With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong value in sheet.
        /// </summary>
        internal static string WrongValueInSheet {
            get {
                return ResourceManager.GetString("WrongValueInSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should.
        /// </summary>
        internal static string YouShould {
            get {
                return ResourceManager.GetString("YouShould", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should not.
        /// </summary>
        internal static string YouShouldNot {
            get {
                return ResourceManager.GetString("YouShouldNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should see.
        /// </summary>
        internal static string YouShouldSee {
            get {
                return ResourceManager.GetString("YouShouldSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should see this Led.
        /// </summary>
        internal static string YouShouldSeeThisLed {
            get {
                return ResourceManager.GetString("YouShouldSeeThisLed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should see this Symbol.
        /// </summary>
        internal static string YouShouldSeeThisSymbol {
            get {
                return ResourceManager.GetString("YouShouldSeeThisSymbol", resourceCulture);
            }
        }
    }
}
